"""canvas foundation schema

Revision ID: a1b70fc2f706
Revises: 
Create Date: 2026-08-22 21:07:45.468453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1b70fc2f706'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # gen_random_uuid() (used as the default for every primary key below) needs
    # pgcrypto. Autogenerate never emits this — see design/merge-doc.md §3.
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('owner_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), server_default='Untitled', nullable=False),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_flags',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('transformation_id', sa.UUID(), nullable=True),
    sa.Column('type', postgresql.ENUM('image', 'video', 'audio', name='asset_type'), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'ready', 'failed', name='asset_status'), server_default='pending', nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('assets_project_idx', 'assets', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('transformations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('node_id', sa.Text(), nullable=True),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', postgresql.ENUM('queued', 'running', 'succeeded', 'failed', name='tx_status'), server_default='queued', nullable=False),
    sa.Column('provider_job_id', sa.Text(), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provider_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('retry_of_id', sa.UUID(), nullable=True),
    sa.Column('cost_credits', sa.Integer(), nullable=True),
    sa.Column('queued_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('visible_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lease_expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint("node_id ~ '^node_[a-zA-Z0-9_-]{12}$'", name='ck_transformations_node_id_format'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retry_of_id'], ['transformations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_transformations_idempotency_key')
    )
    op.create_index('tx_active_idx', 'transformations', ['status', 'started_at'], unique=False, postgresql_where=sa.text("status in ('queued', 'running')"))
    op.create_index('tx_claimable_idx', 'transformations', ['visible_at'], unique=False, postgresql_where=sa.text("status in ('queued', 'running')"))
    op.create_index('tx_one_active_per_node', 'transformations', ['node_id'], unique=True, postgresql_where=sa.text("status in ('queued', 'running')"))
    op.create_index('tx_user_recent_idx', 'transformations', ['user_id', sa.literal_column('queued_at DESC')], unique=False)
    # ### end Alembic commands ###

    # Autogenerate only diffs schema, never data. This is the kill-switch row —
    # see CLAUDE.md "Locked decisions" and design/merge-doc.md §5.4.
    op.execute(
        "insert into system_flags (key, value) values ('generation', '{\"enabled\": true}')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("delete from system_flags where key = 'generation'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tx_user_recent_idx', table_name='transformations')
    op.drop_index('tx_one_active_per_node', table_name='transformations', postgresql_where=sa.text("status in ('queued', 'running')"))
    op.drop_index('tx_claimable_idx', table_name='transformations', postgresql_where=sa.text("status in ('queued', 'running')"))
    op.drop_index('tx_active_idx', table_name='transformations', postgresql_where=sa.text("status in ('queued', 'running')"))
    op.drop_table('transformations')
    op.drop_index('assets_project_idx', table_name='assets')
    op.drop_table('assets')
    op.drop_table('system_flags')
    op.drop_table('projects')
    # ### end Alembic commands ###

    # pgcrypto is intentionally left installed — dropping a shared extension on
    # downgrade risks breaking other objects in the same database that came to
    # depend on it later.
