"""Compatibility shim. Implementation lives in providers.mureka.api."""

from providers.mureka.api import (  # noqa: F401
    GATEWAY_TOOLS,
    TOOL_HANDLERS,
    api_key,
    create_instrumental,
    create_podcast,
    create_song,
    create_song_from_prompt,
    create_speech,
    describe_song,
    dispatch_tool,
    dry_run,
    extend_lyrics,
    extend_song,
    generate_lyrics,
    generate_lyrics_video,
    generate_soundtrack,
    generate_track,
    list_models,
    query_billing,
    query_task,
    recognize_song,
    region_edit_song,
    remix_song,
    stem_song,
    text_to_music,
    transcribe_song,
    upload_file,
    vocal_clone,
)
